### PR TITLE
Addition to tr-TR

### PR DESCRIPTION
**Pull request by Grithz**
I will continue to update this.

### CODE REVIEW

**Comment by TheNoob27** [comment]
that's great! I'll merge this when I've finished the rewrite

**Review by baen — APPROVED** [review]

**Comment by TheNoob27** [comment]
update? it's alright if you don't wanna finish this anymore, but let me know so I can close this

**Comment by Grithz** [comment]
Wow
I completely forgot about this
I will try to complete it

**Review by fatih2424 — CHANGES_REQUESTED** [review]

**Comment by TheNoob27** [comment]
Hey, it's been 3 months

I'm not trying to pressure you to add more translations, but if you don't want to continue this then let me know so I can merge what you have done so far

**Pull request merged**
